### ISSUE TITLE
Support UK signature

### ISSUE THREAD

**Issue by n6g7** [theodo/signature#1]
Cool tool @giregk!

It would be nice to make a few changes to be able to generate a UK-compatible signatures:

- AaU, I can choose which address to display
  For reference our current UK address is:
  ```
  2-7 Clerkenwell Green
  London EC1R 0DE
  ```
- AaU, I can choose the link on the logo (between theodo.fr and theodo.co.uk I guess)
- (nice to have) AaU, I can choose the order of the phone numbers (I'd rather have my UK number first ideally)

**Comment by giregk** [comment]
Thanks n6g7 !! I had not seen this issue, sorry for replying so late. I have added a choice for the country. This choice determines the address that is displayed, the link on the logo, and the order of telephone numbers. Do you think this is enough ?

**Comment by n6g7** [comment]
That's amazing, thanks Gireg! :D
